Schéma ::= CREATE SCHEMA AUTHORIZATION utilisateur
           [Liste-élément-schéma]

élément-schéma ::=   définition-colonne
                   | définition-vue
                   | opération-octroi-privilège

définition-table-de-base ::= CREATE TABLE table-de-base
                             (list-élément-table-de-base(, ))

élément-table-de-base ::=    définition-colonne
                          || définition-contrainte-unicité

définition-colonne ::=    type-colonne [NOT NULL [UNIQUE]]
                       || [définition-clé-primaire]
                       || [définition-clé-étrangère]

définition-contrainte-unicité ::= UNIQUE (liste-colonne(, ))

définition-clé-primaire ::= PRIMARY KEY

définition-clé-étrangère ::= REFERENCE (colonne)

définition-vue ::= CREATE VIEW vue [liste-colonne(, )]
                   AS spécifique-requête
                   [WITH CHECK OPTION]

opération-octroi-privilège  ::= GRANT privilèges ON table
                                TO (list-autorisée(, ))
                                [WITH GRANT]

privilèges ::=   ALL [PRIVILEGES]
               | (liste-opération(, ))

opération ::= SELECT|INSERT|DELETE|UPDATE [liste-colonne(, )]

autorisés ::=   PUBLIC
              | utilisateur
