<?php

use Hoa\Router;

$router = new Router\Http();
$router
    ->get(
        'c',
        '(?<vendor>)/(?<chapter>)\.html'
    )
    ->get(
        'hack',
        '(?<chapter>)\.html'
    )
    ->get(
        'full',
        '/(?<vendor>)/(?<chapter>)\.html'
    )

    ->_get(
        'literature',
        'https://hoa-project.net/Literature\.html'
    )
    ->_get(
        'learn',
        'https://hoa-project.net/Literature/Learn/(?<chapter>)\.html'
    )
    ->get(
        '_resource',
        'https://static.hoa-project.net/(?<resource>)'
    )
    ->_get(
        'central_resource',
        'https://central.hoa-project.net/Resource/(?<path>)'
    )
    ->_get(
        'board',
        'https://waffle.io/hoaproject/(?<repository>)'
    )
    ->_get(
        'git',
        'https://git.hoa-project.net/(?<repository>).git/'
    )
    ->_get(
        'github',
        'https://github.com/hoaproject/(?<repository>)'
    )
    ->_get(
        'research',
        'https://hoa-project.net/Literature/Research/(?<article>[\w\d]+)\.pdf',
        'Literature\Research'
    )
    ->_get(
        'event',
        'https://hoa-project.net/Event/(?<event>\w+)\.html',
        'Generic'
    )
    ->_get(
        'keynote',
        'https://keynote.hoa-project.net/(?<keynote>)'
    );
